from app.modules.common.exceptions import ApplicationException

class UserExistsException(ApplicationException): ...

class UserDoesNotExistException(ApplicationException): ...

class InvalidCredentialsException(ApplicationException): ...